name: Format with Prettier
on:
  push:
    branches: ['main']
    paths:
      - '**.md'
      - '**.yml'
  pull_request:
    branches: ['main']
    paths:
      - '**.md'
      - '**.yml'
  workflow_dispatch:

jobs:
  format-markdown:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install -g prettier

      - name: Format files
        run: prettier --write "**/*.{md,yml}"

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "$(git ls-files '*.md' '*.yml')"
          git commit -m "chore: format files with Prettier [skip ci]"
          git push
