name: Format with Spotless
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
jobs:
  format-check:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run Spotless Check
        run: mvn spotless:check
      - name: Apply Spotless Format
        if: failure()
        run: |
          mvn spotless:apply
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "chore: apply spotless formatting [skip ci]"
            git push
          else
            echo "No changes to commit after running spotless:apply"
          fi
